---
# First Play - Handle Files in all hosts
- name: Play - Handle Files in all hosts
  hosts: all
  tasks:
    - name: all host are identified with a file
      copy:
        content: "My family is {{ ansible_os_family }}"
        dest: "/tmp/family.txt"
        mode: '0644'

# Second Play - for Alpine's Nodejs app
- name: Play - for Alpine's Nodejs app
  hosts: app_group
  tasks:
    - name: NodeJs is installed
      apk:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      loop:
        - nodejs
        - nodejs-npm

    - name: app directory is created
      file:
        path: /node-app
        state: directory

    - name: app is installed
      template:
        src: app.js.j2
        dest: /node-app/app.js

    - name: app dependencies file is copied
      copy:
        src: package.json
        dest: /node-app/package.json

    - name: app dependencies are installed
      npm:
        path: /node-app
        state: present
        production: true

    - name: Install forever (to run Node.js app)
      npm:
        name: forever
        global: yes
        state: present

    - name: Check list of Node.js apps running
      command: forever list
      register: forever_list
      changed_when: false

    - name: Start example Node.js app
      command: forever start /node-app/app.js
      when: "forever_list.stdout.find('/node-app/app.js') == -1"

# Third Play - Install and configure Nginx as a load balancer
- name: Install and configure Nginx as a load balancer
  hosts: localhost
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        update_cache: yes
        state: present

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copy custom Nginx configuration for load balancing
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Restart Nginx to apply new configuration
      service:
        name: nginx
        state: restarted
