all:
  children:
    app_group:
      hosts:
        managedhost-app-1:
          ansible_host: localhost
          ansible_port: 2223
          ansible_user: root
          ansible_ssh_private_key_file: ./secrets/id_rsa
          ansible_connection: ssh
        managedhost-app-2:
          ansible_host: localhost
          ansible_port: 2224
          ansible_user: root
          ansible_ssh_private_key_file: ./secrets/id_rsa
          ansible_connection: ssh
        managedhost-app-3:
          ansible_host: localhost
          ansible_port: 2225
          ansible_user: root
          ansible_ssh_private_key_file: ./secrets/id_rsa
          ansible_connection: ssh
    # Definition for localhost to manage it with Ansible for Nginx setup
    localhost:
      hosts:
        localhost:
          ansible_connection: local
